### ISSUE TITLE
请问这个错误是什么原因造成的啊

### ISSUE THREAD

**Issue by Pyolar** [z814081807/DeepNER#47]
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    training(args)
  File "main.py", line 134, in training
    train_base(opt, train_examples, dev_examples)
  File "main.py", line 44, in train_base
    train(opt, model, train_dataset)
  File "D:\Documents\PycharmProjects\extraction\DeepNER-master\src\utils\trainer.py", line 219, in train
    swa(swa_raw_model, opt.output_dir, swa_start=opt.swa_start)
  File "D:\Documents\PycharmProjects\extraction\DeepNER-master\src\utils\functions_utils.py", line 83, in swa
    model_path_list = get_model_path_list(model_dir)
  File "D:\Documents\PycharmProjects\extraction\DeepNER-master\src\utils\functions_utils.py", line 74, in get_model_path_list
    key=lambda x: (x.split('/')[-3], int(x.split('/')[-2].split('-')[-1])))
  File "D:\Documents\PycharmProjects\extraction\DeepNER-master\src\utils\functions_utils.py", line 74, in <lambda>
    key=lambda x: (x.split('/')[-3], int(x.split('/')[-2].split('-')[-1])))
IndexError: list index out of range

**Comment by 1uxury** [comment]
我也有这个问题，想问一下大佬最后解决了么

**Comment by 1uxury** [comment]
> 我也有这个问题，想问一下大佬最后解决了么

具体怎么解决的，不记得了，大概就是run.bat（我的系统跑不了sh文件，直接改成bat了）文件里各个文件地址不要乱改成完整路径，保持原有的相对路径就行。以及注意斜杠的问题。

<img width="554" height="384" alt="Image" src="https://github.com/user-attachments/assets/9283056b-eb51-4a23-9fd5-2dd4040c4597" />
